version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Brinnley01%21%40%23@db:5432/kitchenhelper
    depends_on:
      - db
      - redis

  frontend:
    build: ./web-frontend
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Brinnley01!@#
      POSTGRES_DB: kitchenhelper
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
